name: Build And Push
on:
    push:
        tags:
            - "*"
    workflow_dispatch:

jobs:
    docker:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Set up QEMU
              uses: docker/setup-qemu-action@v4
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v4
            - name: Login to DockerHub
              uses: docker/login-action@v3
              with:
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_TOKEN }}
            - name: Environment Variable
              id: vars
              run: echo "build_version=$(git describe --tags)" >> $GITHUB_ENV
            - name: Debug Tags
              run: git tag -l
            - name: Build and push
              id: docker_build
              uses: docker/build-push-action@v4
              with:
                  context: .
                  file: Dockerfile
                  platforms: |
                      linux/arm/v7
                      linux/arm64
                      linux/amd64
                  tags: |
                      neouu/pushback:latest
                      neouu/pushback:${{ env.build_version }}
                  push: true
            - name: Image digest
              run: echo ${{ steps.docker_build.outputs.digest }}
