name: Build And Push
on:
  push:
    tags:
      - "*"
  workflow_dispatch:


jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Environment Variable
        id: vars
        run: echo "::set-output name=build_version::$(git describe --tags)"
      - name: Debug Tags
        run: git tag -l
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile
          platforms: |
            linux/arm
            linux/arm64
            linux/amd64
          tags: |
            thurmantsao/alarm-paw-server:latest
            thurmantsao/alarm-paw-server:${{ steps.vars.outputs.build_version }}
          push: true
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
